### PR TITLE
Adds terms for four-cycle harmonic and calculate the R^2 regression stat

### PR DESCRIPTION
**Pull request by cwingard**
Adds the terms for the four-cycle harmonic model, calculates the coefficient of determination (or the R^2) value for the regression statistics (compared to the the original Matlab code and output from the regress function), and updates the description text to refer to the use of the four-cycle model.

### CODE REVIEW

**Review by crisien — APPROVED** [review]
I though we agreed to use the regular stddev calculation so:
_Finally, the standard deviation is derived using the observations for a given month and the  climatological fit for that month as the expected value._
should say:
_Finally, the standard deviation is derived using the observations for a given month._ 

Otherwise the changes look good.

**Review by reedan88 — APPROVED** [review]
Looks good. I have another update coming which does interpolation for the std deviation when months are missing.

**Comment by reedan88** [comment]
@crisien It does calculate it from the observations. I'll fix that in an upcoming PR.

**Comment by cwingard** [comment]
@reedan88 text updated

**Comment by reedan88** [comment]
@cwingard Got it. Thanks.

**Pull request merged**
